from __future__ import annotations
from enum import Enum
from typing import List, Optional
from pydantic import BaseModel, Field


class WorkerStatus(str, Enum):
    IDLE = "idle"
    TRAINING = "training"
    SYNCING = "syncing"
    OFFLINE = "offline"


class DeviceType(str, Enum):
    CUDA = "cuda"
    ROCM = "rocm"
    MPS = "mps"
    CPU = "cpu"



# ── Worker registration ──────────────────────────────────────────────────────

class RegisterRequest(BaseModel):
    worker_id: str                  # stable UUID generated by worker
    device_type: DeviceType
    device_name: str                # e.g. "NVIDIA GeForce RTX 3080"
    vram_gb: float
    ram_gb: float
    num_cpus: int


class RegisterResponse(BaseModel):
    token: str                      # JWT issued by coordinator
    heartbeat_interval: int = 30    # seconds


# ── Heartbeat ────────────────────────────────────────────────────────────────

class HeartbeatRequest(BaseModel):
    worker_id: str
    status: WorkerStatus
    current_job_id: Optional[int] = None
    local_step: Optional[int] = None


class HeartbeatResponse(BaseModel):
    ok: bool
    should_stop: bool = False       # coordinator can abort a training run


# ── Job assignment ───────────────────────────────────────────────────────────

class TrainingConfig(BaseModel):
    model_name: str                 # e.g. "Qwen/Qwen2.5-0.5B"
    hf_id: str = ""                 # HuggingFace model ID (set by coordinator at assignment)
    lora_r: int = 16
    lora_alpha: int = 32
    lora_target_modules: List[str] = Field(default_factory=list)
    num_layers: int = 0
    d_model: int = 0
    num_heads: int = 0
    d_ff: int = 0
    vocab_size: int = 0
    max_seq_len: int = 2048
    local_steps: int = 100          # DiLoCo inner loop H
    learning_rate: float = 3e-4
    weight_decay: float = 0.1
    grad_clip: float = 1.0
    batch_size: int = 8
    dtype: str = "float32"          # "float32" | "float16" | "bfloat16"


class JobAssignment(BaseModel):
    job_id: int
    round: int                      # global sync round number
    shard_id: int                   # which dataset shard this worker owns
    total_shards: int
    config: TrainingConfig
    checkpoint_url: Optional[str] = None   # presigned URL to download weights
    dataset_url: str                       # presigned URL to download shard


# ── Gradient sync ────────────────────────────────────────────────────────────

class SyncResponse(BaseModel):
    accepted: bool
    new_checkpoint_url: Optional[str] = None   # updated weights after aggregation
    next_round: Optional[int] = None
    message: str = ""


